[9.0][FIX] report_qweb_pdf_watermark
OCA/reporting-engine pull request #154
Opened 2017-07-28 10:38 UTC by mreficent

Backport of https://github.com/OCA/reporting-engine/pull/144.

2017-07-28 12:29 UTC, astirpe requested changes

2017-07-28 12:29 UTC, astirpe commented on report_qweb_pdf_watermark/models/report.py
> +from pyPdf.pdf import PdfFileWriter, PdfFileReader
Why this line was changed?

2017-07-28 12:36 UTC, mreficent commented on report_qweb_pdf_watermark/models/report.py
> +from pyPdf.pdf import PdfFileWriter, PdfFileReader
Because otherwise my PyCharm says unresolved reference  😙

2017-07-28 12:51 UTC, aheficent commented
![image](https://user-images.githubusercontent.com/19620251/28717948-1f46ba0c-73a4-11e7-9d36-acacbb2b2db8.png)
This error is showing in all the Pull Request in v9. This PR is meant to solve that but it's not working. Can anybody the label Needed help here?

2017-07-28 14:30 UTC, astirpe commented
Can you try to backport the entire commit https://github.com/OCA/reporting-engine/commit/7d621022b00b473b734f1e0d7cb19727012be8af? I mean deleting also the obsolete rows in `.travis.yml`.

I'm not sure this will fix the problem though.

2017-07-28 14:43 UTC, mreficent commented
I fully backported the two commits of that PR but both merged into only one.

2017-07-28 16:20 UTC, astirpe commented
@mreficient it seems you missed a commit. Can you double check? Take a look at the commit mentioned in my previous post and then look at your commits.

2017-07-28 16:24 UTC, mreficent commented
https://github.com/OCA/reporting-engine/pull/154/commits/623f86e2672d0132bde0ab1a2fe2529ca53804bd is a squashed version of https://github.com/OCA/reporting-engine/pull/144/commits/6dacecae08baf881a3e0c7f9cd665e464fe41ddf and https://github.com/OCA/reporting-engine/pull/144/commits/7d621022b00b473b734f1e0d7cb19727012be8af.

2017-08-30 08:04 UTC, hbrunn commented
this finally is fixed in #141 by now

2017-08-30 08:04 UTC, closed without merging