[8.0][ADD] report_xlsx_helper
OCA/reporting-engine pull request #234
Opened 2018-08-15 10:36 UTC by luc-demeyer

backport of 10.0 report_xlsx_helper module

2018-08-15 14:07 UTC, luc-demeyer commented
@astirpe : can you review (I fixed a couple of flake8/pylint issues in your modules to greenify this PR).

2018-08-16 08:03 UTC, pankk requested changes

2018-08-16 08:03 UTC, pankk commented on report_xlsx_helper/README.rst
> +Excel report engine helpers
Rename helpers to helper

2018-08-16 08:03 UTC, pankk commented on report_xlsx_helper/__openerp__.py
> +    'name': 'Report xlsx helpers',
Rename helpers to helper

2018-08-16 08:18 UTC, pankk approved these changes
Successful functional test with six custom xlsx reports using this helper.

2018-08-16 09:25 UTC, luc-demeyer commented on report_xlsx_helper/__openerp__.py
> +    'name': 'Report xlsx helpers',
This module add a set tools to facilitate the creation of XLSX files, hence I think 'helpers' in the README is more appropriate.

2018-08-17 07:04 UTC, pankk commented on report_xlsx_helper/__openerp__.py
> +    'name': 'Report xlsx helpers',
Ok, I didn't think of it that way. I began to think of it as a "helper module". I think usually such a module would be named in plural form anyway, but the singular convention is a good measure for headache avoidance. But I now agree that the description should use the plural form to be accurate.

2022-03-06 12:24 UTC, closed without merging