report_xlsx: fix report context propagation on records
OCA/reporting-engine pull request #259
Opened 2018-12-04 12:06 UTC by simahawk

Without this change If you return a custom action that sets a custom context -> you lose it -> if you report depends on it... it's broken :sob: 

@adrienpeiffer @sbidoul this fixes XLS export on `mis.report.instance` :wink:

2018-12-04 12:31 UTC, simahawk commented
digging into this issue turns out that if you don't pass `data` [in the action you return](https://github.com/OCA/mis-builder/blob/11.0/mis_builder/models/mis_report_instance.py#L567), you won't get anything into `data` [in the controller ](https://github.com/OCA/reporting-engine/blob/11.0/report_xlsx/controllers/main.py#L12) :thinking:

2018-12-04 13:18 UTC, sbidoul commented
@simahawk in mis builder 10, we have this https://github.com/OCA/mis-builder/blob/be28ba9de4c67bbc4339522bdb1686b4e942ada3/mis_builder/models/mis_report_instance.py#L618-L627 and it works fine.

2018-12-04 13:38 UTC, simahawk commented
@sbidoul but that code has been migrated already to v11 since there's not `get_action`.
Anyway, the issue is not there. What you have in mis_builder now is:
```py
return {
            'name': 'MIS report instance XLSX report',
            'model': 'mis.report.instance',
            'type': 'ir.actions.report',
            'report_name': 'mis_builder.mis_report_instance_xlsx',
            'report_type': 'xlsx',
            'report_file': 'mis_report_instance',
            'context': context,
        }
```
and this does not work.
If I apply this patch, it does not work neither, unless I change the dict above like:
```py
[...]
            'context': context,
            'data': {'__make_report_controller_work__': 1},
```
by adding `data` key. However, its content doesn't matter...

2019-04-28 15:02 UTC, sbidoul commented
@simahawk is this still WIP?

2019-04-29 14:31 UTC, simahawk commented
@sbidoul I'm not working on this since ages :sweat_smile: 
Actually I was waiting for feedback, especially on the fact that we have to add a fake `data` dict anyhow to make it work :man_shrugging:

2019-04-29 14:37 UTC, sbidoul commented
All I can say is the fake data dict is needed to propagate the context for pdf reports too. So at least the hack is consistent ;) Why it is so is beyond me...

2019-04-29 14:40 UTC, simahawk commented
> Why it is so is beyond me...

It's because the controller relies on the automatic conversion of the params in the request and if the param is not in the request they ignore it completely :man_facepalming:

2019-04-29 14:41 UTC, simahawk commented
ok then I'll update this PR w/ a mention in the docs

2019-04-29 17:55 UTC, sbidoul commented
@simahawk I just debugged a bit, and I think the context is actually lost here:

https://github.com/OCA/reporting-engine/blob/9eb9a4248c4a08649ca6b8d6708f1fe2917f25df/report_xlsx/models/ir_report.py#L19-L21

So replacing that with `with_context(active_model=self.model)` (plus the data hack in the report action), it seems to work.

2019-06-10 12:38 UTC, simahawk commented
I removed context manipulation and fixed up the places where the context was replaced instead of updated. I cannot test it now, I'll see if someone else can.

2019-09-23 21:01 UTC, jffernandez requested changes
I think that to fix the context propagation only is needed one change, with that it works.
See inline comments.
Thank you for your PR!

2019-09-23 21:01 UTC, jffernandez commented on report_xlsx/controllers/main.py
> +            xlsx = report.with_context(**context).render_xlsx(
Why is this needed? It works without that change.
This context is created from self.env.context, then updated.
No need to update the actual context again with all the dict from the context var.

2019-09-23 21:01 UTC, jffernandez commented on report_xlsx/models/ir_report.py
> +        return report_obj.with_context(**context).search(conditions, limit=1)
Why is this needed? It works without that change.
You don't need to update the context for searching that object (to be consistent with other controllers, too) because you will update the context before using it.

2019-09-23 21:01 UTC, jffernandez commented on report_xlsx_helper/controllers/main.py
> +            xlsx = report.with_context(**context).render_xlsx(
Why is this needed? It works without that change.
This context is created from self.env.context, then updated.
No need to update the actual context again with all the dict from the context var.

2019-09-23 21:01 UTC, jffernandez commented on report_xlsx/report/report_xlsx.py
> +        return self.env[self.env.context['active_model']].browse(ids)
Not really needed for the fix you're addressing. If the active model name is not there, it will fail anyway.
Keep the changes to the minimun needed.

2019-10-21 15:41 UTC, sbidoul commented on report_xlsx/report/report_xlsx.py
> +        return self.env[self.env.context['active_model']].browse(ids)
Here the error message will be more explicit (`KeyError`) so it's worthwhile even if not strictly necessary to fix the context propagation bug.

2019-10-21 15:42 UTC, sbidoul approved these changes
@simahawk if you'd have 2 minutes to revert the `**context` changes which are not really necessary?

For the rest I tested and the fix works fine. Thanks!

2019-10-21 16:02 UTC, simahawk commented
I changed "blindly" what have you asked for, no time to test, sorry guys :/

2019-10-21 16:04 UTC, sbidoul commented
Thanks!

/ocabot merge patch

fixes #326

2019-10-21 16:28 UTC, merged