12.0 mig report_xml
OCA/reporting-engine pull request #295
Opened 2019-06-10 18:07 UTC by ernestotejeda

The code has been adapted to version 12 using part of the odoo core code and modifying it

Cc @Tecnativa

2019-06-10 18:11 UTC, etobella commented
There is a Pr for this migration, but no answers from the developer...

2019-06-10 18:13 UTC, pedrobaeza commented
Yes, superseeding...

2019-06-10 18:29 UTC, etobella approved these changes
Working as expected.

Travis is Red, but it is only lint issues. I also added some lint reviews non blocking 👍

2019-06-10 18:29 UTC, etobella commented on report_xml/static/src/js/report/action_manager_report.js
> +});
Missing new line

2019-06-10 18:29 UTC, etobella commented on report_xml/views/webclient_templates.xml
> +</odoo>
Missing new line

2019-06-10 18:59 UTC, ernestotejeda commented
@etobella , lints fixed

2019-06-11 08:09 UTC, pedrobaeza approved these changes

2019-06-11 15:42 UTC, Tardo requested changes

2019-06-11 15:42 UTC, Tardo commented on report_xml/controllers/main.py
> +                converter = extension = 'xml'
Does a better reading make up for this? maybe better to think of a more generic variable name instead of use two for the same value?

2019-06-11 15:42 UTC, Tardo commented on report_xml/models/report_action.py
> +import logging
:fire:

2019-06-11 15:42 UTC, Tardo commented on report_xml/models/report_action.py
> +_logger = logging.getLogger(__name__)
:fire:

2019-06-12 13:12 UTC, ernestotejeda commented
@Tardo , Could you review again ?

2019-06-12 15:35 UTC, Tardo requested changes

2019-06-12 15:35 UTC, Tardo commented on report_xml/controllers/main.py
> +                        filename = "%s.'xml'" % (report_name)
Please, remove single quotes.
```suggestion
                        filename = "%s.xml" % (report_name)
```

2019-06-12 15:47 UTC, ernestotejeda commented on report_xml/controllers/main.py
> +                        filename = "%s.'xml'" % (report_name)
Oh, thank you @Tardo , done

2019-06-12 15:59 UTC, Tardo approved these changes
LGTM :+1:

2019-06-12 16:11 UTC, merged