[ADD][13.0] new module report_layout_config
OCA/reporting-engine pull request #363
Opened 2020-01-10 16:20 UTC by Tonow-c2c

![image](https://user-images.githubusercontent.com/32262135/72168319-393f8d80-33cd-11ea-9e0c-7422a5a498ad.png)

------

### Result:
[Draft Invoice (_ 2)-5.pdf](https://github.com/OCA/reporting-engine/files/4046543/Draft.Invoice._.2.-5.pdf)

2020-01-15 11:41 UTC, grindtildeath requested changes
Two things. Moreover I don't think reporting-engine is the right repository for such a module, but I'm not sure which one would be the best. I guess OCA/web would fit better since we have a dependency on the module..

2020-01-15 11:41 UTC, grindtildeath commented on report_layout_config/views/res_company.xml
> +                  <field name="full_header_img" widget="image"/>
IMO these fields should be made available in the General Settings wizard under the Business Documents section and displayed only if `external_layout_images` is selected. (means you have to declare related fields on the `res.config.settings`)

2020-01-15 11:41 UTC, grindtildeath commented on report_layout_config/models/res_company.py
> +    full_footer_img = fields.Binary(string="Full footer image", help="This image will replace all footer.")
Add attachment=True on both fields.

2020-01-17 13:25 UTC, Tonow-c2c commented
@grindtildeath for the module place @gurneyalex suggest me to put on this repo :-)

2020-01-17 13:42 UTC, jcoux requested changes

2020-01-17 13:42 UTC, jcoux commented on report_layout_config/__manifest__.py
> +    "summary": "Add possibility to easely modify the global report layout",
```suggestion
    "summary": "Add possibility to easily modify the global report layout",
```

2020-01-17 13:42 UTC, jcoux commented on report_layout_config/data/report_layout.xml
> +    <data>
`data` element is useless.

2020-01-17 13:42 UTC, jcoux commented on report_layout_config/models/__init__.py
> +
```suggestion
```

2020-01-17 13:42 UTC, jcoux commented on report_layout_config/models/base_document_layout.py
> +                wizard.need_images_layout = True
```
    @api.depends('report_layout_id')
    def _compute_need_images_layout(self):
        img_lay = self.env.ref(
            'report_layout_config.external_layout_images_template'
        )
        for wizard in self:
            wizard.need_images_layout = (
                wizard.external_report_layout_id == img_lay_id
            )
```

2020-01-17 13:42 UTC, jcoux commented on report_layout_config/models/base_document_layout.py
> +            elif wizard.external_report_layout_id.id != img_lay_id:
```suggestion
            elif wizard.external_report_layout_id != img_lay:
```
And change related lines.

2020-01-17 13:42 UTC, jcoux commented on report_layout_config/models/base_document_layout.py
> +                super()._compute_preview()
```suggestion
                super(BaseDocumentLayout, wizard)._compute_preview()
```
Or remove loop and and `self.ensure_one()`

2020-01-17 13:42 UTC, jcoux commented on report_layout_config/readme/DESCRIPTION.rst
> +This module provides new report template.
```suggestion
This module provides new report template
```

2020-01-17 13:42 UTC, jcoux commented on report_layout_config/readme/DESCRIPTION.rst
> +With possibility to add image to replace header and footer.
```suggestion
with possibility to add image to replace header and footer.
```

2020-01-17 13:42 UTC, jcoux commented on report_layout_config/templates/report_templates.xml
> +              <div class="col-9 text-right" style="margin-top:22px;" t-field="company.report_header" name="moto"/>
```suggestion
              <div class="col-9 text-right" style="margin-top:22px;" t-field="company.report_header" name="report_header"/>
```

2020-01-17 13:42 UTC, jcoux commented on report_layout_config/templates/report_templates.xml
> +
```suggestion
```

2020-01-17 13:42 UTC, jcoux commented on report_layout_config/templates/report_templates.xml
> +    <!-- Same as odoo/src/odoo/addons/base/wizard/base_document_layout_views.xml -->
Can be cool to indicate by inline comments which parts are modified.

2020-01-17 13:42 UTC, jcoux commented on report_layout_config/templates/report_templates.xml
> +          </div>
Strange indentation.

2020-01-17 14:47 UTC, jcoux approved these changes

2020-03-23 11:26 UTC, grindtildeath approved these changes
LG :+1:

2020-03-23 11:26 UTC, grindtildeath commented on report_layout_config/models/base_document_layout.py
> +            qweb_ctx.update({"company": self, "res_company": self.company_id})
Looks like this change was unneeded.

2020-08-18 16:22 UTC, gurneyalex commented
/ocabot merge nobump

2020-08-18 16:39 UTC, merged