[14.0][MIG] report_csv: Migration to 14.0
OCA/reporting-engine pull request #442
Opened 2020-10-15 20:20 UTC by tupaq

2020-10-19 15:34 UTC, tonygalmiche approved these changes
LGTM : Functional review only with runbot

![image](https://user-images.githubusercontent.com/150344/96472953-5d1fe180-1231-11eb-9288-20c732fa5e8a.png)

2020-10-30 15:04 UTC, LoisRForgeFlow approved these changes
Code review LGTM

2020-10-30 15:04 UTC, LoisRForgeFlow commented
/ocabot merge nobump

2020-10-30 15:20 UTC, LoisRForgeFlow commented
@tupaq there are some issues with pre-commit, could you rebase your branch and run it again? https://travis-ci.com/github/OCA/reporting-engine/jobs/421650683

2020-11-04 13:52 UTC, tupaq commented
> @tupaq there are some issues with pre-commit, could you rebase your branch and run it again? https://travis-ci.com/github/OCA/reporting-engine/jobs/421650683

Rebased

2020-11-30 14:25 UTC, LoisRForgeFlow commented
Something must have been not clean because you have a merge commit in your history, could you please try again? to clarify, when I say rebase I mean to do a git rebase operation in this pr's branch on top of latest oca/14.0.

2021-02-17 00:13 UTC, davejames requested changes

2021-02-17 00:13 UTC, davejames commented on report_csv/__manifest__.py
> +    "external_dependencies": {"python": ["python-csv"]},
do we need to depend on python-csv? It seems that only csv is being used in the code which is what the dependency was in v13.

2022-09-11 12:33 UTC, closed without merging