[15.0] Migration of base_comment_template
OCA/reporting-engine pull request #619
Opened 2022-04-26 19:07 UTC by alan196

### Proposed changes

Migration PR for module base_comment_template.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

2022-06-27 03:20 UTC, JuanyDForgeflow approved these changes
LGTM

2022-07-25 09:59 UTC, marylla commented
@alan196 Hi there, could you please rebase? I would like to test it on runboat.

2022-07-27 08:41 UTC, rousseldenis commented
@alan196

2022-07-28 12:15 UTC, alan196 commented
@marylla @rousseldenis rebased 👍 sorry I was on holidays

2022-08-03 09:05 UTC, victoralmau commented
I see many changes from v14 that are not in the history (specifically since May 26), can you add them?

2022-08-18 17:24 UTC, alan196 commented
@victoralmau updated with latest changes of V14 👍

2022-08-19 06:30 UTC, victoralmau requested changes
Can you resolve pre-commit and test errors?

2022-08-19 06:30 UTC, victoralmau commented on base_comment_template/models/comment_template.py
> +        self, comment, engine="jinja", add_context=None, post_process=False
```suggestion
        self, comment, engine="jinja", add_context=None, post_process=False
```

According to the documentation, `jinja` is not allowed in this function: https://github.com/odoo/odoo/blob/15.0/addons/mail/models/mail_render_mixin.py#L489

2022-09-02 06:55 UTC, victoralmau commented
Superseed by: https://github.com/OCA/reporting-engine/pull/646

2022-09-02 06:57 UTC, closed without merging