[14.0][MIG] report_qweb_element_page_visibility: Migrate to version 14.0
OCA/reporting-engine pull request #634
Opened 2022-07-05 08:31 UTC by hailangvn

2022-07-14 12:17 UTC, leemannd commented
Hello @hailangvn Could you have a look at the pre-commit?

2022-07-14 13:54 UTC, yvaucher requested changes
A typo in a loop uses an index instead of the value which looks suspicious.
Otherwise LGTM

2022-07-14 13:54 UTC, yvaucher commented on report_qweb_element_page_visibility/views/layouts.xml
> +                        var y = document.getElementsByClassName(klass);
The index is passed instead of the value.
```suggestion
                        var y = document.getElementsByClassName(operations[klass]);
```

2022-07-15 01:39 UTC, hailangvn commented on report_qweb_element_page_visibility/views/layouts.xml
> +                        var y = document.getElementsByClassName(klass);
Thanks @yvaucher for your review. The `klass` variable actually has class name for `document.getElementsByClassName(klass)` to finds elements those have that class name. `operations[klass]` [is used later](https://github.com/OCA/reporting-engine/pull/634/files/69d7f2ea90049f1434fdf8d5a1dc7054ab628ffe#diff-dccb17f982a6e7808bdaef034c15750c683d740aabc43c69e07c9157520c483dR51) to execute corresponding function.

2022-07-15 03:28 UTC, hailangvn commented
Thanks @leemannd for the comment. This PR has been updated.

2022-07-18 09:07 UTC, santostelmo approved these changes

2022-08-12 18:38 UTC, extrememicro approved these changes
LGTM
functional review ok.

2022-09-16 10:55 UTC, Abranes approved these changes
Functional review

LGTM

2022-12-20 08:50 UTC, simahawk commented
/ocabot migration report_qweb_element_page_visibility

2022-12-21 13:41 UTC, yvaucher approved these changes

2022-12-21 13:42 UTC, yvaucher commented
/ocabot merge nobump

2022-12-21 13:47 UTC, merged

2022-12-21 16:24 UTC, cvinh commented
I did another PR here https://github.com/OCA/reporting-engine/pull/702 not to lose this improvment