[15.0][MIG] base_comment_template: Migration to 15.0
OCA/reporting-engine pull request #646
Opened 2022-09-02 06:53 UTC by victoralmau

Superseed: https://github.com/OCA/reporting-engine/pull/619

Migration to 15.0

Please @pedrobaeza and @CarlosRoca13 can you review it?

@Tecnativa TT35696

2022-09-02 07:46 UTC, pedrobaeza commented
/ocabot migrationbase_comment_template

2022-09-02 07:47 UTC, pedrobaeza commented
/ocabot migration base_comment_template

2022-09-02 07:50 UTC, pedrobaeza requested changes
Please add a commit on top of the previous one with your changes instead of blending them with the existing.

2022-09-02 07:50 UTC, pedrobaeza commented on base_comment_template/wizard/base_comment_template_preview_views.xml
> +    <!-- SMS Template Preview -->
This has no sense

2022-09-02 07:50 UTC, pedrobaeza commented on base_comment_template/wizard/base_comment_template_preview.py
> +        default="inline_template",
A migration script is needed to convert existing values to this new one.

2022-09-10 03:51 UTC, hailangvn approved these changes
Functional test ok. Thanks for the work.

2022-09-13 07:23 UTC, marylla commented
@victoralmau Can you please update your PR as Pedro suggested. Thank you! :)

2022-09-13 15:21 UTC, victoralmau commented
The commits are already separated and I have added the migration script to convert the text of templates.

2022-09-15 07:55 UTC, marylla commented
@pedrobaeza Can you review again please?

2022-09-15 17:43 UTC, pedrobaeza reviewed
Missed `jinja` to `inline_template` value mapping

2022-09-16 06:41 UTC, victoralmau commented
> Missed `jinja` to `inline_template` value mapping

Sorry, I don't understand exactly what you mean.

The engine change from `jinja` to `inline_template` is only used in wizard to rendering the comment.

2022-09-16 06:44 UTC, pedrobaeza approved these changes
OK, seen

2022-09-16 06:44 UTC, pedrobaeza commented
/ocabot merge nobump

2022-09-16 07:50 UTC, merged