[9.0][FIX] report_xls: Move description to first line
OCA/reporting-engine pull request #66
Opened 2016-08-12 23:41 UTC by lasley

I'm not sure why the [RunBot builds are failing](https://runbot.odoo-community.org/runbot/build/3152292) on a non-installable module, but they are and it's killing my OCD. 

This is minimalistic change that hopefully fixes the builds.

2016-08-13 00:46 UTC, elicoidal commented on report_xls/__openerp__.py
> +    'description': """Excel report engine
Simply remove the description key. This is not mandatory anymore with the README file.
(even more this becomes redundant and difficult to keep in sync)

2016-08-15 16:37 UTC, lasley commented on report_xls/__openerp__.py
> +    'description': """Excel report engine
In this instance there isn't a ReadMe, and I was trying to keep the change-set minimal as this isn't a full conversion & I am just trying to fix the build. If this is a block however, I will move this over to a ReadMe using OCA template.

2016-08-15 20:06 UTC, pedrobaeza commented on report_xls/__openerp__.py
> +    'description': """Excel report engine
You can cherry-commit https://github.com/OCA/reporting-engine/commit/fddca415b8d255b9d877ea92217ea086205ce077 from 8.0

2016-08-15 20:18 UTC, lasley commented on report_xls/__openerp__.py
> +    'description': """Excel report engine
Excellent call, thanks @pedrobaeza

2016-08-26 18:04 UTC, lasley commented
Oops forgot to drop a note saying comments handled after handling comments. Comments handled! 😄

2016-09-28 14:06 UTC, atchuthan commented on report_xls/__openerp__.py
> +    'description': """Excel report engine
you could remove the description field as README.rst was added

2016-11-17 10:08 UTC, pedrobaeza requested changes
Although the module is not yet merged, but we can fast-track it anyway.

2016-11-17 10:08 UTC, pedrobaeza approved these changes

2016-11-17 10:08 UTC, merged