[MIG] report_substitute: Migration to 16.0
OCA/reporting-engine pull request #700
Opened 2022-12-14 17:34 UTC by matiasperalta1

2023-04-03 11:52 UTC, amkarthik approved these changes

2023-04-04 07:15 UTC, atchuthan approved these changes
Functional QA :+1:

2023-04-20 10:52 UTC, HviorForgeFlow commented
I would migrate it directly from v13 to v16 if it your requirement. Other contributors that may need it in previous versions will backport it.

2023-04-20 10:54 UTC, HviorForgeFlow requested changes

2023-04-20 10:54 UTC, HviorForgeFlow commented on report_substitute/demo/action_report.xml
> +    <record
That's not right. Here you have an example of how to transform report tags to record: I would migrate it directly from v13 to v16 if it your requirement. Other contributes that may need it in previous versions will backport it.

I also recommend you to read those wikis when migrating: 
https://github.com/OCA/maintainer-tools/wiki#migration

2023-05-11 08:16 UTC, HviorForgeFlow approved these changes

2023-05-11 08:16 UTC, HviorForgeFlow commented
/ocabot merge nobump

2023-05-11 08:31 UTC, merged