[15.0][IMP] report_qweb_pdf_watermark: Improvements
OCA/reporting-engine pull request #748
Opened 2023-04-07 16:28 UTC by bosd

2023-04-28 15:15 UTC, bosd commented
@espo-tony Can you review?

2023-07-02 19:26 UTC, thomaspaulb requested changes

2023-07-02 19:26 UTC, thomaspaulb commented on report_qweb_pdf_watermark/models/report.py
> +            logger.error("No usable watermark found, got %s...", watermark[:100])
You've swapped the two checks around, but shouldn't the check for `if not pdf_watermark` come first? The other check actually goes into pdf_watermark.numPages, so seems like it should come after.

2023-07-02 19:26 UTC, thomaspaulb commented on report_qweb_pdf_watermark/models/report.py
> +        if pdf_watermark.numPages > 1:
This refactor doesn't really do anything

2023-07-02 19:27 UTC, thomaspaulb commented
Is this a cherry-pick of a fix for another version?

2023-07-10 12:20 UTC, bosd commented
> Is this a cherry-pick of a fix for another version?

Yes, These are improvements made by @espo-tony.

2023-07-10 13:22 UTC, thomaspaulb commented
Can you help out with a link to the original PR

2023-07-11 07:38 UTC, bosd commented
> Can you help out with a link to the original PR

No, as these changes were made in private repo. 
For that reason I'm committing it here.  :smile: 

>This refactor doesn't really do anything
True, maybe better code practice/readability of the code.

Feel free to close/merge close this pr.

2023-07-14 16:27 UTC, thomaspaulb commented on report_qweb_pdf_watermark/tests/test_report_qweb_pdf_watermark.py
> +    def _test_pdf_has_usable_pages(self, pdf_watermark):
Also, this test is disabled?!

2023-07-14 16:28 UTC, thomaspaulb commented
@bosd Yes, it doesn't seem to me that this does anything useful. So I'll close it.

2023-07-14 16:28 UTC, closed without merging