[IMP] report_async: Change schedule_time to Datetime field
OCA/reporting-engine pull request #904
Opened 2024-07-01 09:30 UTC by RicardCForgeFlow

2024-07-03 08:08 UTC, HviorForgeFlow approved these changes

2024-07-03 09:15 UTC, MiquelRForgeFlow requested changes

2024-07-03 09:15 UTC, MiquelRForgeFlow commented on report_async/models/report_async.py
> +    schedule_time = fields.Datetime(string='Schedule Time')
This would need migration scripts. Can we adapt the code in a way to avoid this change?

2024-07-03 14:23 UTC, MiquelRForgeFlow approved these changes

2024-07-07 08:49 UTC, HviorForgeFlow commented
/ocabot merge major

2024-07-07 08:57 UTC, merged