[18.0][MIG] bi_sql_editor: Migration to 18.0
OCA/reporting-engine pull request #938
Opened 2024-10-10 04:24 UTC by thienvh332

### Ported PRs
- #620
- #805
### Depend on:
- https://github.com/oca/reporting-engine/pull/937

2024-10-23 14:45 UTC, henrybackman requested changes
Small change requests but overall looks good :+1:

2024-10-23 14:45 UTC, henrybackman commented on bi_sql_editor/models/bi_sql_view_field.py
> +        relation_fields = self.env["ir.model.fields"].search(
According to the migration guide the access to "ir.model.*" methods is removed in 15:
- https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0
but is this still a valid use? Not familiar with this so just wanted to raise a question.

2024-10-23 14:45 UTC, henrybackman commented on bi_sql_editor/models/bi_sql_view.py
> +        return super().unlink()
Should use `@api.ondelete` instead
- https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

2024-10-23 14:45 UTC, henrybackman commented on bi_sql_editor/models/bi_sql_view.py
> +        readonly=True,
Could the `readonly` fields be marked as `readonly` in the view instead?
- https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

2024-10-23 14:45 UTC, henrybackman commented on bi_sql_editor/views/view_bi_sql_view.xml
> +    <record id="view_bi_sql_view_tree" model="ir.ui.view">
This and other references to `tree` should be changed to `list`
- https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0

2024-10-28 10:15 UTC, sebalix reviewed
LG, small remarks

2024-10-28 10:15 UTC, sebalix commented on bi_sql_editor/models/bi_sql_view.py
> +                req = f"DROP TABLE {sql_view.view_name}"
Better to use `sql.SQL` and `sql.Identifier` from `psycopg2` instead to avoid SQL injection, see https://www.psycopg.org/docs/sql.html

2024-10-28 10:15 UTC, sebalix commented on bi_sql_editor/models/bi_sql_view.py
> +            WHERE   attrelid = '{self.view_name}'::regclass
Same remark

2024-10-28 10:15 UTC, sebalix commented on bi_sql_editor/models/bi_sql_view.py
> +                '{sql_view.view_name}'
Same remark

2024-10-31 14:13 UTC, lef-adhoc approved these changes

2024-10-31 14:13 UTC, JrAdhoc approved these changes
LGTM

2024-11-04 15:47 UTC, henrybackman approved these changes

2024-11-28 18:00 UTC, sebalix commented
Hello @thienvh332 , you can drop your `DON'T MERGE` commit, all dependencies have been merged now :) Thanks!

2024-11-29 05:23 UTC, thienvh332 commented
>  you can drop your `DON'T MERGE` commit, all dependencies have been merged now :) Thanks!

Hi @sebalix ,
Thanks, I updated it.

2024-11-29 11:23 UTC, sebalix approved these changes

2024-11-29 13:03 UTC, sebalix reviewed
Getting back on my review, I couldn't create SQL objects on a demo report (on runbot):
![image](https://github.com/user-attachments/assets/a9149c3d-03e9-4d29-a888-7366ae04364e)
Can you check this please?

2024-12-02 03:21 UTC, thienvh332 commented
Hi @sebalix,
The problem comes from my side, sorry about that.

I fixed it. Thanks

2024-12-04 13:22 UTC, HviorForgeFlow approved these changes

2024-12-04 13:22 UTC, HviorForgeFlow commented
/ocabot merge nobump

2024-12-04 13:26 UTC, merged