[18.0][MIG] report_qweb_parameter: Migration to 18.0
OCA/reporting-engine pull request #939
Opened 2024-10-10 07:16 UTC by ramiadavid

2024-11-10 18:34 UTC, xaviedoanhduy requested changes

2024-11-10 18:34 UTC, xaviedoanhduy commented on report_qweb_parameter/models/ir_qweb.py
> +            raise ValidationError(_("Length cannot be less than %s") % str(min_length))
```suggestion
            raise ValidationError(self.env._("Length cannot be less than %s") % str(min_length))
```
could you apply this https://github.com/odoo/odoo/commit/b794f0f332f473deb2c04eba60baf4761db3b508

2024-11-10 18:34 UTC, xaviedoanhduy commented on report_qweb_parameter/demo/test_report_field_length.xml
> +                t-esc="docs[0].street"
```suggestion
                t-out="docs[0].street"
```
`t-esc` and `t-raw` are deprecated output directives: https://www.odoo.com/documentation/18.0/developer/reference/frontend/qweb.html

2025-01-15 14:56 UTC, ValentinVinagre commented
Hi @ramiadavid please add this commit: 
https://github.com/OCA/reporting-engine/pull/964/commits/375c9f8a8ecd78eb4bcfa62e778fefd777eb1d04

2025-01-23 20:02 UTC, ramiadavid commented on report_qweb_parameter/demo/test_report_field_length.xml
> +                t-esc="docs[0].street"
done

2025-01-23 20:02 UTC, ramiadavid commented on report_qweb_parameter/models/ir_qweb.py
> +            raise ValidationError(_("Length cannot be less than %s") % str(min_length))
done

2025-01-23 20:03 UTC, ramiadavid commented
> Hi @ramiadavid please add this commit: [375c9f8](https://github.com/OCA/reporting-engine/commit/375c9f8a8ecd78eb4bcfa62e778fefd777eb1d04)

done

2025-01-24 01:45 UTC, xaviedoanhduy approved these changes
minor adjustment

2025-01-24 01:47 UTC, xaviedoanhduy approved these changes
minor adjustment
but LGTM

2025-01-24 01:47 UTC, xaviedoanhduy commented on report_qweb_parameter/models/ir_qweb.py
> +                self.env._("Length cannot be more than %s") % str(max_length)
```suggestion
                self.env._("Length cannot be more than %s", max_length)
```

2025-01-24 01:47 UTC, xaviedoanhduy commented on report_qweb_parameter/models/ir_qweb.py
> +                self.env._("Length cannot be less than %s") % str(min_length)
```suggestion
                self.env._("Length cannot be less than %s", min_length)
```

2025-05-07 08:00 UTC, xaviedoanhduy requested changes

2025-05-07 08:00 UTC, xaviedoanhduy approved these changes

2025-05-26 11:49 UTC, svilaLevel4 approved these changes

2025-06-04 19:48 UTC, HviorForgeFlow commented
/ocabot merge nobump

2025-06-04 19:54 UTC, merged