[18.0][MIG] report_substitute: Migration to 18.0
OCA/reporting-engine pull request #948
Opened 2024-10-28 17:38 UTC by matiasperalta1

2024-12-24 06:09 UTC, atchuthan requested changes
Pre-commit and tests are failing in this PR. Please check @matiasperalta1 
We are having problems when we add this PR to git-aggregator.

Functionally :+1:

2025-04-22 14:18 UTC, marielejeune commented
Hi @matiasperalta1 
Are you planning to fix pipeline? 
Thanks

2025-06-12 10:45 UTC, samirGuesmi commented
I opened a new PR here [#1033 ]

2025-06-13 11:24 UTC, sbejaoui commented
Hi @matiasperalta1,

please check the last two commits of #1033

2025-11-16 12:36 UTC, closed without merging