[18.0][MIG] report_qweb_element_page_visibility: Migration to 18.0
OCA/reporting-engine pull request #956
Opened 2024-12-05 14:50 UTC by BT-dlagin

2024-12-10 13:40 UTC, BT-dmoreno approved these changes

2024-12-12 09:53 UTC, BT-dlagin commented
@legalsylvain hello, would it be possible to do a review here?
Thanks!

2024-12-17 18:55 UTC, BT-dlagin commented
@AaronHForgeFlow hello, kindly asking for review.
Thanks! :)

2025-01-02 14:36 UTC, BT-dlagin commented
@OCA/reporting-engine-maintainers hello, can somebody do a review for me?
Thanks! :)

2025-02-12 09:03 UTC, StefanRijnhart requested changes
Please include https://github.com/OCA/reporting-engine/pull/882. If you port a module, it is always a good idea to review open, as well as recently merged PRs. That's how I found this one.
When you pick the commit from #882, do change the commit message to feature the module name.

2025-03-10 11:07 UTC, BT-dlagin commented
> Please include #882. If you port a module, it is always a good idea to review open, as well as recently merged PRs. That's how I found this one. When you pick the commit from #882, do change the commit message to feature the module name.

Hello, thanks for your reply.
Cherry pick is done.
Asked for review, thanks!

2025-03-10 11:58 UTC, StefanRijnhart approved these changes
Perfect, thank you for picking the fix from #882!

Functional test and code review.

2025-03-10 12:12 UTC, pedrobaeza commented
/ocabot migration report_qweb_element_page_visibility
/ocabot merge nobump

2025-03-10 12:17 UTC, merged